### ISSUE TITLE
Description field overwritten when annotating chained task on "done"

### ISSUE THREAD

**Issue by kiil** [Matt-Deacalion/Taskwarrior-Chained#2]
If you have a chained task ready for completion and you finish it like so

    task ID done sometext

the description field of the newly completed task will become overwritten with something like:

    annotations:'[{'entry': '20230816T085840Z', 'description': 'sometext'}]'

The description field should stay the same.

**Comment by Matt-Deacalion** [comment]
[Fixed](https://codeberg.org/Dokana/Taskwarrior-Chained/issues/1#issuecomment-1068648).
